"""
Database Seeder - Project Kancil
Populates the database with initial sample questions for development 
and testing purposes.
"""

import logging
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from src.models import Question  # Ensure this matches your model import path

async def seed_questions(session: AsyncSession):
    """
    Inserts sample instructional questions if the database is empty.
    This helps developers verify the 'Safe to Fail' feedback loop immediately.
    """
    # Check if questions already exist to avoid duplicate seeding
    result = await session.execute(select(Question).limit(1))
    existing_question = result.scalars().first()
    
    if existing_question:
        logging.info("🌱 Database already contains data. Skipping seeder.")
        return 

    logging.info("🌱 Seeding initial instructional data...")
    
    # Example 1: Physics Question (Image-based placeholder)
    sample_physics = Question(
        # Note: In production, file_ids are generated by Telegram. 
        # This placeholder is used for architecture testing.
        image_file_id="AgACAgUAAxkBAAICQmX_placeholder", 
        subject="Physics",
        topic="Force and Motion II",
        correct_option="B",
        reference_data={
            "textbook": "KSSM Physics Form 4",
            "page": 45,
            "explanation": (
                "According to Newton's Second Law (F = ma), when mass is constant, "
                "the acceleration of an object is directly proportional to the "
                "net force acting on it."
            )
        },
        is_active=True
    )
    
    # Example 2: Chemistry Question
    sample_chem = Question(
        subject="Chemistry",
        topic="The Mole Concept",
        correct_option="C",
        reference_data={
            "textbook": "KSSM Chemistry Form 4",
            "page": 72,
            "explanation": "One mole of any substance contains 6.02 x 10^23 particles."
        },
        is_active=True
    )
    
    session.add_all([sample_physics, sample_chem])
    
    try:
        await session.commit()
        logging.info("✅ Seeding complete: 2 instructional questions inserted.")
    except Exception as e:
        await session.rollback()
        logging.error(f"❌ Seeding failed: {e}")